### ISSUE TITLE
AI integration

### ISSUE THREAD

**Issue by tothradoslav** [mingo-app/mingo#642]
- [ ]  schema analyzer - create schema based on a couple of documents
- [ ]  documents - suggest query based on description + documents sample
- [ ]  nodeshell - describe what you want and let him suggest the code / function
- [ ]  aggregator - suggestions based on description

**Comment by mattivilola** [comment]
Great idea. Would be useful. Also could analyze current indeces and suggest better ones.

**Comment by alkanna** [comment]
> Also could analyze current indeces and suggest better ones.

How so? Suggesting indexes could only be relevant by analyzing your application queries.

**Comment by muhammedfurkan** [comment]
maybe index suggestions

**Comment by mattivilola** [comment]
missed the previous comment and reply to it, but Mingo already has access to index and related index sizes, no. of uses, etc. data. I suppose it is also possible to access query logs if enabling profiling and that should reveal additional information for this purpose.. right? I could assume "AI" could then identify slow queries and suggest index to add and to remove index which is never used e.g. if running it for some time, longer the better of course.. Not sure if this could work, but if yes, would be dope!

**Comment by muhammedfurkan** [comment]
when are the new updates coming?

**Comment by tothradoslav** [comment]
We are considering the actual implementation of AI into Mingo. This feature is more complex than we thought, not technically, rather in pricing / economy. The major issue is how / who would pay for the AI services (tokens used). There could potentially be millions of tokens used by a user. This would probably not be possible to cover in current pricing plans. A few ideas / options:

1. use a free API, not very realistic.
2. create a new plan for AI users to cover the token-costs
3. allow users to enter their own AI subscriptions (chatgpt, claude, etc..)

If you have further ideas, please let us know.

**Comment by Christilut** [comment]
Maybe consider using a light/mini model and limit the tokens a user can go through. It's not very expensive at all. I have it on for all my users with only a safety/abuse limit (that no one ever hits) and I pay a few dollars a month (gpt5-mini). I would just go for it with a limit you can control on the server and keep an eye on the costs. There's probably cheaper models out there that are more focused on code results as well.

Personally I would love this in mingo because when I have a complex query (or even a simple one, it's less thinking and faster) then I throw it in chatgpt or claude and paste the results. Having actual knowledge of my database schema as well would be so good. Even better if it could ask follow up questions if there is any confusion. 

Nodeshell suggestions would be useful too for sure.

I don't really see AI being useful in index suggestions, that's not AI business but a feature that can analyze a collection.

I would focus on query building since it creates the most value without the complexity. Keep it simple first :)

**Comment by tothradoslav** [comment]
This has been fixed and released in version [2026.2.0](https://github.com/mingo-app/mingo/releases/tag/v2026.2.0).

Thank you for reporting this issue!

**Comment by muhammedfurkan** [comment]
thanks for the ai asistant.

The added AI models are very outdated and obsolete. Can you update the model lists?

**Comment by tothradoslav** [comment]
Any specifics you have in mind? I added the latest ones, but will only be available in next release.
